// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onDistanceChange();
void onHumidityChange();
void onMovingDelayChange();
void onNeededKChange();
void onNeededNChange();
void onNeededPChange();
void onNeededWaterChange();
void onNitrogenChange();
void onPhosphorusChange();
void onPlantedSeedsChange();
void onPotassiumChange();
void onSeedsChange();
void onTemperatureChange();
void onFlagChange();

int distance;
int humidity;
int movingDelay;
int neededK;
int neededN;
int neededP;
int neededWater;
int nitrogen;
int phosphorus;
int plantedSeeds;
int potassium;
int seeds;
int temperature;
bool flag;

void initProperties(){

  ArduinoCloud.addProperty(distance, READWRITE, ON_CHANGE, onDistanceChange);
  ArduinoCloud.addProperty(humidity, READWRITE, ON_CHANGE, onHumidityChange);
  ArduinoCloud.addProperty(movingDelay, READWRITE, ON_CHANGE, onMovingDelayChange);
  ArduinoCloud.addProperty(neededK, READWRITE, 10 * SECONDS, onNeededKChange);
  ArduinoCloud.addProperty(neededN, READWRITE, ON_CHANGE, onNeededNChange);
  ArduinoCloud.addProperty(neededP, READWRITE, ON_CHANGE, onNeededPChange);
  ArduinoCloud.addProperty(neededWater, READWRITE, 10 * SECONDS, onNeededWaterChange);
  ArduinoCloud.addProperty(nitrogen, READWRITE, ON_CHANGE, onNitrogenChange);
  ArduinoCloud.addProperty(phosphorus, READWRITE, ON_CHANGE, onPhosphorusChange);
  ArduinoCloud.addProperty(plantedSeeds, READWRITE, ON_CHANGE, onPlantedSeedsChange);
  ArduinoCloud.addProperty(potassium, READWRITE, ON_CHANGE, onPotassiumChange);
  ArduinoCloud.addProperty(seeds, READWRITE, ON_CHANGE, onSeedsChange);
  ArduinoCloud.addProperty(temperature, READWRITE, ON_CHANGE, onTemperatureChange);
  ArduinoCloud.addProperty(flag, READWRITE, ON_CHANGE, onFlagChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
