# Generated by Django 5.0.3 on 2024-03-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NPKSensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "nitrogen_level",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "phosphorus_level",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "potassium_level",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
    ]
