# Generated by Django 5.0.3 on 2024-03-28 16:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NPKSensor",
            new_name="NPKReading",
        ),
    ]
